[build]
  command = "npm run build"
  publish = "dist"
  environment = { NODE_VERSION = "16" }

# Opting your Website out of Google's FLoC Network
[[headers]]
  for = "/"
    [headers.values]
    Access-Control-Allow-Origin = ""
    Access-Control-Allow-Methods = ""
    Access-Control-Allow-Headers = ""